### ISSUE TITLE
The remote code isn't memorized

### ISSUE THREAD

**Issue by daformat** [bertrandboudaud/FreeboxMiniRemote#1]
Over quitting the app and relaunching it, the remote code has to be entered again, is this some kind of regression or didn't you implement the feature? One would expect not to have to enter it again and again.

System: OS X 10.8.4

**Comment by bertrandboudaud** [comment]
Hi Daformat,

It is supposed to save user data, and it does it with my setup, but you are the second user to report the issue, so i've looked what could be the reason and tried a fix, please check it.

You will find here, click on download link:
http://bertrandboudaud.github.io/FreeboxMiniRemote/
(carefully refresh the web page as the link has changed)

hope it'll be fixed.

thanks!
bertrand

**Comment by daformat** [comment]
That's perfect! It now works rightfully :+1: 
I won't ever have to remember that code again ;) Way better!

Thanks for being so quick to fix it!
